/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GLWrap */

#ifndef _Included_GLWrap
#define _Included_GLWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GLWrap
 * Method:    defaultOpenGLSettings
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GLWrap_defaultOpenGLSettings
  (JNIEnv *, jobject);

/*
 * Class:     GLWrap
 * Method:    createWindow
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_GLWrap_createWindow
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     GLWrap
 * Method:    glfwWindowShouldClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_GLWrap_glfwWindowShouldClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GLWrap
 * Method:    glfwPollEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GLWrap_glfwPollEvents
  (JNIEnv *, jobject);

/*
 * Class:     GLWrap
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_GLWrap_glClearColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     GLWrap
 * Method:    glClearColorDepthBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GLWrap_glClearColorDepthBuffer
  (JNIEnv *, jobject);

/*
 * Class:     GLWrap
 * Method:    glfwSwapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GLWrap_glfwSwapBuffers
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GLWrap
 * Method:    glfwTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GLWrap_glfwTerminate
  (JNIEnv *, jobject);

/*
 * Class:     GLWrap
 * Method:    deleteGL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GLWrap_deleteGL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
