/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImguiWrap */

#ifndef _Included_ImguiWrap
#define _Included_ImguiWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ImguiWrap
 * Method:    initializeImGUI
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ImguiWrap_initializeImGUI
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ImguiWrap
 * Method:    newFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ImguiWrap_newFrame
  (JNIEnv *, jobject);

/*
 * Class:     ImguiWrap
 * Method:    render
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ImguiWrap_render
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ImguiWrap
 * Method:    renderDrawData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ImguiWrap_renderDrawData
  (JNIEnv *, jobject);

/*
 * Class:     ImguiWrap
 * Method:    guiUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ImguiWrap_guiUpdate
  (JNIEnv *, jobject);

/*
 * Class:     ImguiWrap
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ImguiWrap_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
